#
# CodeCov.io Configuration
# https://docs.codecov.io/docs/codecovyml-reference
#

#
# https://docs.codecov.io/docs/fixing-paths
#
fixes:
  - "megameklab/::"        # reduce root e.g., "before/path/" => "path/"

#
# https://docs.codecov.io/docs/ignoring-paths
#
ignore:
  - "megamek"

github_checks:
  #
  # https://docs.codecov.io/docs/github-checks-beta#disabling-github-checks-patch-annotations-via-yaml
  #
  annotations: false
